# Generated by Django 3.2.7 on 2021-09-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='order_status',
            new_name='discount_status',
        ),
    ]
