# Generated by Django 3.2.7 on 2021-09-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_order_status_discount_discount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_amount',
            field=models.CharField(max_length=5),
        ),
    ]
