# Generated by Django 3.2.7 on 2021-09-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_products', models.JSONField()),
                ('order_status', models.CharField(choices=[('confirmed', 'confirmed'), ('cancelled', 'cancelled'), ('on the way', 'on the way'), ('delivered', 'delivered'), ('', 'Not Selected')], db_index=True, default='', help_text='status of the order', max_length=30)),
                ('date_submitted', models.DateField(auto_now=True)),
                ('products', models.ManyToManyField(to='product.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customer.customer')),
            ],
        ),
    ]
