# Generated by Django 3.2.7 on 2021-09-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_number_of_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_of_products',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
